catalogs:
  cli:
    ansis: ^4.2.0
    cac: ^6.7.14
  dev:
    '@types/node': ^24.6.1
    eslint: ^9.36.0
    eslint-typegen: ^2.3.0
    husky: ^9.1.7
    nano-staged: ^0.8.0
    tsdown: ^0.15.6
    tsx: ^4.20.6
    typescript: ^5.9.3
  main:
    '@antfu/eslint-config': ^5.4.1
    eslint-flat-config-utils: ^2.1.4
    local-pkg: ^1.1.2
  plugin:
    eslint-plugin-de-morgan: ^2.0.0
  test:
    vitest: ^3.2.4
