catalogs:
  cli:
    ansis: ^4.1.0
    cac: ^6.7.14
  dev:
    '@types/node': ^24.1.0
    eslint: ^9.31.0
    eslint-typegen: ^2.3.0
    nano-staged: ^0.8.0
    simple-git-hooks: ^2.13.0
    tsdown: ^0.13.0
    tsx: ^4.20.3
    typescript: ^5.8.3
  main:
    '@antfu/eslint-config': ^5.0.0
    eslint-flat-config-utils: ^2.1.0
    local-pkg: ^1.1.1
  plugin:
    '@nuxt/eslint-plugin': '*'
    eslint-plugin-de-morgan: ^1.3.0
  test:
    vitest: ^3.2.4
