catalogs:
  cli:
    ansis: ^4.1.0
    cac: ^6.7.14
  dev:
    '@types/node': ^24.0.1
    eslint: ^9.28.0
    eslint-typegen: ^2.2.0
    nano-staged: ^0.8.0
    simple-git-hooks: ^2.13.0
    tsdown: ^0.12.7
    tsx: ^4.20.1
    typescript: ^5.8.3
  main:
    '@antfu/eslint-config': ^4.14.1
    eslint-flat-config-utils: ^2.1.0
    local-pkg: ^1.1.1
  plugin:
    eslint-plugin-de-morgan: ^1.3.0
