shellEmulator: true

trustPolicy: no-downgrade

catalogs:
  cli:
    cac: ^6.7.14
  dev:
    '@types/node': ^25.3.0
    eslint: ^10.0.1
    eslint-typegen: ^2.3.1
    husky: ^9.1.7
    nano-staged: ^0.9.0
    tsdown: ^0.20.3
    tsx: ^4.21.0
    typescript: ^5.9.3
  inline:
    es-toolkit: ^1.44.0
  main:
    '@antfu/eslint-config': ^7.4.3
    eslint-flat-config-utils: ^3.0.1
    local-pkg: ^1.1.2
  plugin:
    '@e18e/eslint-plugin': ^0.2.0
    eslint-plugin-de-morgan: ^2.0.0
  test:
    vitest: ^4.0.18
