catalogs:
  cli:
    ansis: ^4.1.0
    cac: ^6.7.14
  dev:
    '@types/node': ^24.2.0
    eslint: ^9.32.0
    eslint-typegen: ^2.3.0
    husky: ^9.1.7
    nano-staged: ^0.8.0
    tsdown: ^0.13.1
    tsx: ^4.20.3
    typescript: ^5.9.2
  main:
    '@antfu/eslint-config': ^5.2.0
    eslint-flat-config-utils: ^2.1.1
    local-pkg: ^1.1.1
  plugin:
    '@nuxt/eslint-plugin': '*'
    eslint-plugin-de-morgan: ^1.3.1
  test:
    vitest: ^3.2.4
